Date: December 8th Yanice commit
project-200/project200.org pull request #4
Opened 2024-12-08 21:00 UTC by YaniceSze

Footer CoreValues TeamSection and FAQ added.

2024-12-10 12:11 UTC, ssaini4 requested changes

2024-12-10 12:11 UTC, ssaini4 commented on src/components/ui/footer.tsx
> +    <footer className="bg-black text-white py-6">
background here is `#202020`

2024-12-10 12:11 UTC, ssaini4 commented on src/components/ui/coreValues.tsx
> +            <FolderIcon className="text-gray-500" fontSize="large" />
this icon needs to be the outline Folder icon. See:
![Screenshot 2024-12-10 at 7 08 35 AM](https://github.com/user-attachments/assets/15098e42-f32d-411f-bba6-5808d5af095e)

2024-12-10 12:11 UTC, ssaini4 commented on src/components/ui/socialMedia.tsx
> +      </a>
These icons need to have a circle background. See

![Screenshot 2024-12-10 at 7 09 42 AM](https://github.com/user-attachments/assets/6bd8db5f-e18d-479e-b73f-2cb5b36f5d99)

2024-12-10 12:11 UTC, ssaini4 commented on src/components/ui/team.tsx
> +                        className="block mb-6 rounded-full object-cover"
These images don't need to be rounded and should be bigger. See:
![Screenshot 2024-12-10 at 7 11 01 AM](https://github.com/user-attachments/assets/26dca7e5-8cb3-44aa-ae1b-c2bbba09ca20)

2024-12-12 22:28 UTC, YaniceSze commented
Changes implemented but didn't find the correct icon for the facebook. The one I found is only for the paid version.

2024-12-18 00:01 UTC, ssaini4 commented
Thank you for the fixes and address the comments @YaniceSze. This looks good to me! 👍

2024-12-18 00:01 UTC, merged